# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

search_best_split_cpp <- function(Z, Y, min_node_size, n_quantiles = NULL) {
    .Call('_gadget_search_best_split_cpp', PACKAGE = 'gadget', Z, Y, min_node_size, n_quantiles)
}

search_best_split_point_cpp <- function(z, Y, n_quantiles = NULL, is_categorical = FALSE, min_node_size = 1L) {
    .Call('_gadget_search_best_split_point_cpp', PACKAGE = 'gadget', z, Y, n_quantiles, is_categorical, min_node_size)
}

