# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calculate_ale_heterogeneity_single_cpp <- function(dL, interval_index) {
    .Call('_gadget_calculate_ale_heterogeneity_single_cpp', PACKAGE = 'gadget', dL, interval_index)
}

calculate_ale_heterogeneity_list_cpp <- function(Y) {
    .Call('_gadget_calculate_ale_heterogeneity_list_cpp', PACKAGE = 'gadget', Y)
}

re_mean_center_ice_cpp <- function(Y, grid, idx) {
    .Call('_gadget_re_mean_center_ice_cpp', PACKAGE = 'gadget', Y, grid, idx)
}

search_best_split_cpp <- function(Z, Y, min_node_size, n_quantiles = NULL) {
    .Call('_gadget_search_best_split_cpp', PACKAGE = 'gadget', Z, Y, min_node_size, n_quantiles)
}

search_best_split_point_cpp <- function(z, Y, n_quantiles = NULL, is_categorical = FALSE, min_node_size = 1L) {
    .Call('_gadget_search_best_split_point_cpp', PACKAGE = 'gadget', z, Y, n_quantiles, is_categorical, min_node_size)
}

